CpG_file="data/CpG_lists/Stubbs_clock_CpGs.csv"
G4_file_minus="data/G4_maps/G4s_mouse_minus.bed"
G4_file_plus="data/G4_maps/G4s_mouse_plus.bed"
chain_file="-"
genome_file="data/genome_files/mm10_chromInfo.txt"
output_file="out/Stubbs_FE.csv"
name="Stubbs"
window_size_CpG_dist_plot="50"
